jobs:

# jobs for the box demo pipelines for PROD environment

################################

# 5) add deploy config for PROD

# BOX JOBS

# # PROD deployment - Amazon ECS
#   - name: box-prod-ecs
#     type: deploy
#     steps:
#       - IN: box-test-aws-ecs
#         trigger: false
#       - IN: box-p-scaler
#       - IN: box-p-ecs-params
#       - IN: env-prod-ecs
#       - IN: trigger-prod-deploy-box
#       - TASK: managed

# PROD deployment - Joyent Triton
  - name: box-prod-triton
    type: deploy
    steps:
      - IN: box-test-triton
        trigger: false
      - IN: box-p-tpc-params
      - IN: box-p-scaler
      - IN: env-prod-triton
      - IN: trigger-prod-deploy-box
