triggers:
  - name: trigger-prod-deploy-box
    type: trigger
    version:
      message: "deploy box to prod 4"

  - name: trigger-prod-deploy-dv
    type: trigger
    version:
      message: 'deploy dv to prod'
