jobs:

# jobs for the box demo pipelines for PROD environment

################################

# 5) add deploy config for PROD

# BOX JOBS

# PROD deployment - Amazon ECS
  - name: box-prod-ecs
    type: ecsDeploy
    steps:
      - IN: demo-rel
        trigger: false
        versionName: v1.0.2
      - IN: box-p-ecs-params
      - IN: box-p-scaler
      - IN: env-prod-ecs
      - IN: trigger-prod-deploy-box
      - TASK: managed

# PROD deployment - Amazon ECS
  - name: dv-prod-ecs
    type: ecsDeploy
    steps:
      - IN: demo-rel
        trigger: false
        versionName: v1.0.2
      - IN: dv-p-ecs-params
      - IN: dv-p-scaler
      - IN: env-prod-ecs
      - IN: trigger-prod-deploy-dv
      - TASK: managed


# # PROD deployment - Joyent Triton
#   - name: box-prod-triton
#     type: tripubDeploy
#     steps:
#       - IN: box-test-triton
#         trigger: false
#       - IN: box-p-tpc-params
#       - IN: box-p-scaler
#       - IN: env-prod-triton
#       - IN: trigger-prod-deploy-box
